import { SituationModel } from "../types/situation";

export const DEMO_SCENARIOS: Record<string, SituationModel> = {
  "flood-disaster": {
    id: "sit-flood-001",
    rawInput: {
      storyText:
        "The rain flooded our ground-floor apartment last night. My daughter's school laptop and textbooks are completely soaked, my birth certificate and lease papers are wet and unreadable, and we have nowhere safe to sleep tonight. The landlord isn't answering their phone and I don't know what assistance I can apply for.",
      hasMedia: true,
      mediaTypes: ["image/jpeg"],
      mediaName: "water_damaged_documents.jpg",
    },
    metadata: {
      analyzedAt: new Date().toISOString(),
      modelUsed: "gemini-2.5-flash (multimodal reasoning)",
      overallSeverity: "critical",
      summary:
        "Severe residential flood causing immediate displacement of a 2-person household with school-age child. Severe secondary cascading impacts across vital records destruction, educational interruption, and potential landlord dispute.",
      primaryDomain: "Disaster Emergency & Housing Displacement",
      isDemoOrSimulated: true,
    },
    evidence: [
      {
        id: "ev-01",
        source: "user_story",
        content: "The rain flooded our ground-floor apartment last night.",
        confidence: 1.0,
      },
      {
        id: "ev-02",
        source: "user_story",
        content: "we have nowhere safe to sleep tonight.",
        confidence: 1.0,
      },
      {
        id: "ev-03",
        source: "user_story",
        content: "My daughter's school laptop and textbooks are completely soaked",
        confidence: 1.0,
      },
      {
        id: "ev-04",
        source: "user_story",
        content: "my birth certificate and lease papers are wet and unreadable",
        confidence: 1.0,
      },
      {
        id: "ev-05",
        source: "uploaded_image",
        content: "Visual confirmation: Saturated paper documents showing mold risk and illegible state seal.",
        confidence: 0.96,
      },
      {
        id: "ev-06",
        source: "user_story",
        content: "The landlord isn't answering their phone",
        confidence: 1.0,
      },
    ],
    facts: [
      {
        id: "fact-01",
        statement: "Ground-floor apartment inundated by rain flood water.",
        evidenceId: "ev-01",
      },
      {
        id: "fact-02",
        statement: "Household is without safe sleeping shelter for tonight.",
        evidenceId: "ev-02",
      },
      {
        id: "fact-03",
        statement: "Minor dependent's educational equipment (laptop, textbooks) ruined.",
        evidenceId: "ev-03",
      },
      {
        id: "fact-04",
        statement: "Primary identity (birth certificate) and tenancy documentation destroyed.",
        evidenceId: "ev-04",
      },
      {
        id: "fact-05",
        statement: "Property owner/landlord currently unresponsive.",
        evidenceId: "ev-06",
      },
    ],
    inferences: [
      {
        id: "inf-01",
        inference: "Emergency housing intake will be blocked or delayed without identity affidavit due to lost birth certificate and lease.",
        rationale: "Municipal housing assistance programs require verified resident status and photo ID.",
        confidence: 0.94,
      },
      {
        id: "inf-02",
        inference: "Daughter is at imminent risk of unexcused absence and lost schoolwork unless McKinney-Vento liaison is notified.",
        rationale: "Federal McKinney-Vento Act mandates immediate school support and tech replacement for displaced students.",
        confidence: 0.98,
      },
      {
        id: "inf-03",
        inference: "Unresponsive landlord indicates need for formal written notice of uninhabitable premises to protect tenant security deposit and rent withholding rights.",
        rationale: "Implied warranty of habitability breaches require certified paper/electronic record.",
        confidence: 0.91,
      },
    ],
    unknowns: [
      {
        id: "unk-01",
        question: "What municipality or county is the flooded apartment located in?",
        whyNeeded: "Determines jurisdiction for emergency Red Cross congregate shelter vs municipal hotel vouchers.",
        blockedActionIds: ["act-01", "act-03"],
        suggestedOptions: ["Metropolitan County", "State Emergency Zone", "Other"],
      },
      {
        id: "unk-02",
        question: "Does the tenant hold an active renters insurance policy?",
        whyNeeded: "Determines whether temporary living expenses (ALE) are covered privately or require public disaster relief.",
        blockedActionIds: ["act-06"],
        suggestedOptions: ["Yes, active policy", "No renters insurance", "Unsure / Need to verify"],
      },
    ],
    needs: [
      {
        id: "need-shelter",
        category: "shelter",
        title: "Immediate Emergency Shelter",
        description: "Secure safe overnight accommodations for parent and child within next 6 hours.",
        urgency: "immediate_24h",
        trustState: "USER_PROVIDED",
        evidenceIds: ["ev-02"],
        whyReasoning: "Directly stated: 'we have nowhere safe to sleep tonight.' High vulnerability due to dependent child.",
        systemIds: ["sys-redcross", "sys-211"],
        blockingNeedIds: [],
        actionIds: ["act-01", "act-02"],
      },
      {
        id: "need-docs",
        category: "document_recovery",
        title: "Vital Records & Tenancy Recovery",
        description: "Obtain expedited replacement birth certificate and sworn residency affidavit.",
        urgency: "urgent_72h",
        trustState: "USER_PROVIDED",
        evidenceIds: ["ev-04", "ev-05"],
        whyReasoning: "User reported birth certificate and lease wet and illegible. Confirmed via photo inspection.",
        systemIds: ["sys-vital", "sys-housingauth"],
        blockingNeedIds: [],
        actionIds: ["act-03", "act-04"],
      },
      {
        id: "need-edu",
        category: "education",
        title: "Displaced Student Educational Continuity",
        description: "Deploy McKinney-Vento homeless liaison protections for school laptop replacement and transport.",
        urgency: "urgent_72h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-03"],
        whyReasoning: "Gemini recognized soaked laptop and textbooks threaten schooling; McKinney-Vento guarantees no-cost device reissue.",
        systemIds: ["sys-schooldistrict"],
        blockingNeedIds: [],
        actionIds: ["act-05"],
      },
      {
        id: "need-legal",
        category: "legal_administrative",
        title: "Habitability Notice & Landlord Escalation",
        description: "Submit certified electronic notice of uninhabitable conditions and preserve tenancy rights.",
        urgency: "medium_term",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-06"],
        whyReasoning: "Landlord silence during active flood creates legal jeopardy for deposit and rent obligations.",
        systemIds: ["sys-tenantaid"],
        blockingNeedIds: [],
        actionIds: ["act-06"],
      },
    ],
    systems: [
      {
        id: "sys-redcross",
        name: "American Red Cross Disaster Services",
        agencyType: "ngo_relief",
        purpose: "Emergency non-congregate hotel vouchers & basic necessity kits.",
        contactChannel: "1-800-RED-CROSS (Dispatch: 24/7)",
        requiredDocuments: ["Photo ID or Self-Attestation Affidavit", "Proof of Address if available"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration. No live dispatch triggered.",
      },
      {
        id: "sys-211",
        name: "United Way 2-1-1 Emergency Triage",
        agencyType: "government",
        purpose: "Municipal family shelter bed registry and storm relief funds.",
        contactChannel: "Dial 2-1-1 or visit 211.org",
        requiredDocuments: ["Family composition info", "Zip code"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-vital",
        name: "State Department of Vital Statistics",
        agencyType: "government",
        purpose: "Emergency expedited birth certificate issuance under disaster protocol.",
        contactChannel: "vitalrecords.state.gov/disaster-expedite",
        requiredDocuments: ["Secondary ID (Work badge, Utility bill scan, or Notarized statement)"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-schooldistrict",
        name: "Public Schools McKinney-Vento Liaison",
        agencyType: "school_district",
        purpose: "Instant loaner Chromebook, textbook replacement, and emergency transportation.",
        contactChannel: "studentservices.district.k12.org",
        requiredDocuments: ["Student ID number or School Name"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-tenantaid",
        name: "Metropolitan Tenants Rights Council",
        agencyType: "legal_aid",
        purpose: "Emergency habitability letter templates and rent escrow counseling.",
        contactChannel: "legalhelp@tenantscouncil.org",
        requiredDocuments: ["Photos of flood damage", "Copy of lease (or landlord name)"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
    ],
    actions: [
      {
        id: "act-01",
        needId: "need-shelter",
        systemId: "sys-redcross",
        title: "Call Red Cross Disaster Intake for Overnight Placement",
        instruction: "Request immediate emergency non-congregate hotel placement for 1 adult and 1 child displaced by storm flooding.",
        priority: "P0_critical",
        trustState: "USER_PROVIDED",
        prerequisiteActionIds: [],
        timeframe: "Immediately (Within 2 hours)",
        deliverableType: "phone_call",
        scriptOrTemplate: {
          headline: "Red Cross Intake Phone Script",
          body: "Hello, my name is [Name]. My ground-floor apartment flooded tonight due to the storm. I am displaced with my school-age daughter and our home is uninhabitable. We have no safe shelter tonight. We need emergency hotel voucher placement. Our current location is [Location].",
        },
        status: "pending",
      },
      {
        id: "act-02",
        needId: "need-shelter",
        systemId: "sys-211",
        title: "Register Household with 2-1-1 Municipal Relief Roster",
        instruction: "Establish case number to ensure eligibility for subsequent county rehousing grants.",
        priority: "P0_critical",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: ["act-01"],
        timeframe: "Before 8:00 PM Tonight",
        deliverableType: "phone_call",
        scriptOrTemplate: {
          headline: "2-1-1 Intake Protocol",
          body: "I am calling to register a flood displacement case for family disaster assistance. Water ingress in living quarters, dependent child in household, unlivable conditions.",
        },
        status: "pending",
      },
      {
        id: "act-03",
        needId: "need-docs",
        systemId: "sys-vital",
        title: "Submit Disaster-Fee-Waiver Vital Records Application",
        instruction: "Order emergency certified birth certificate copy using secondary verification (social security number / digital tax return).",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "Tomorrow morning (Day 2)",
        deliverableType: "form_submission",
        scriptOrTemplate: {
          headline: "Disaster Fee Waiver Letter",
          body: "To the Registrar: Requesting expedited certified birth certificate under State Disaster Relief Order #2026-F. Saturated original destroyed during flood event.",
        },
        status: "pending",
      },
      {
        id: "act-04",
        needId: "need-docs",
        systemId: "sys-vital",
        title: "Photograph and Bag Damaged Documents for Forensic Recovery",
        instruction: "Do NOT discard wet papers. Place in sealed freezer bags to arrest mold and preserve identifiable serial stamps.",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "Within 12 hours",
        deliverableType: "document_safekeeping",
        status: "pending",
      },
      {
        id: "act-05",
        needId: "need-edu",
        systemId: "sys-schooldistrict",
        title: "Email McKinney-Vento District Liaison for Loaner Device",
        instruction: "Disclose displacement status to unlock guaranteed emergency equipment replacement and excused attendance.",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "Tomorrow 8:30 AM",
        deliverableType: "form_submission",
        scriptOrTemplate: {
          headline: "Student Support Notification",
          body: "Dear School Liaison, Our family suffered residential flooding last night. My daughter [Child Name, Grade X] had her school laptop and books destroyed and we are temporarily displaced. Under McKinney-Vento provisions, please issue a loaner device and notify her teachers of emergency attendance flexibility.",
        },
        status: "pending",
      },
      {
        id: "act-06",
        needId: "need-legal",
        systemId: "sys-tenantaid",
        title: "Send Formal Uninhabitability Notice to Landlord with Photo Log",
        instruction: "Create timestamped written trail putting landlord on notice of defective conditions and pausing liability.",
        priority: "P2_normal",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: ["act-04"],
        timeframe: "Within 48 hours",
        deliverableType: "notification",
        scriptOrTemplate: {
          headline: "Notice of Breach of Warranty of Habitability",
          body: "To [Landlord/Property Manager]: Notice is hereby given that premises at [Address] have flooded and are currently uninhabitable. In accordance with state tenant protection code, immediate remediation or termination of lease without penalty is requested.",
        },
        status: "pending",
      },
    ],
    relationships: [
      {
        id: "rel-01",
        sourceId: "need-shelter",
        targetId: "act-01",
        relationType: "resolves_need",
        label: "Requires immediate phone outreach",
      },
      {
        id: "rel-02",
        sourceId: "need-docs",
        targetId: "act-03",
        relationType: "resolves_need",
        label: "Unlocks state identity reissue",
      },
      {
        id: "rel-03",
        sourceId: "act-03",
        targetId: "need-shelter",
        relationType: "depends_on",
        label: "Long-term rehousing voucher requires identity verification",
      },
      {
        id: "rel-04",
        sourceId: "need-edu",
        targetId: "act-05",
        relationType: "resolves_need",
        label: "Activates federal school protections",
      },
      {
        id: "rel-05",
        sourceId: "act-04",
        targetId: "act-06",
        relationType: "depends_on",
        label: "Evidence photos must accompany legal landlord notice",
      },
    ],
  },

  "sudden-layoff": {
    id: "sit-layoff-002",
    rawInput: {
      storyText:
        "I was laid off yesterday without any severance. My company health insurance terminates this Friday, my insulin prescription runs out in four days, and our apartment rent is due in six days. I've never been unemployed before and I'm completely lost on where to file or get medical coverage.",
      hasMedia: false,
    },
    metadata: {
      analyzedAt: new Date().toISOString(),
      modelUsed: "gemini-2.5-flash (multimodal reasoning)",
      overallSeverity: "critical",
      summary:
        "Sudden income loss with acute life-safety prescription cliff (insulin exhaustion within 96 hours) compounded by near-term eviction threat and employer insurance expiration.",
      primaryDomain: "Employment Shock & Healthcare Continuity",
      isDemoOrSimulated: true,
    },
    evidence: [
      {
        id: "ev-11",
        source: "user_story",
        content: "I was laid off yesterday without any severance.",
        confidence: 1.0,
      },
      {
        id: "ev-12",
        source: "user_story",
        content: "my insulin prescription runs out in four days",
        confidence: 1.0,
      },
      {
        id: "ev-13",
        source: "user_story",
        content: "My company health insurance terminates this Friday",
        confidence: 1.0,
      },
      {
        id: "ev-14",
        source: "user_story",
        content: "our apartment rent is due in six days.",
        confidence: 1.0,
      },
      {
        id: "ev-15",
        source: "user_story",
        content: "I've never been unemployed before and I'm completely lost",
        confidence: 1.0,
      },
    ],
    facts: [
      {
        id: "fact-11",
        statement: "Employment terminated without financial severance cushion.",
        evidenceId: "ev-11",
      },
      {
        id: "fact-12",
        statement: "Critical chronic medication (insulin) depletes in under 96 hours.",
        evidenceId: "ev-12",
      },
      {
        id: "fact-13",
        statement: "Employer-provided group health insurance ends in under 72 hours.",
        evidenceId: "ev-13",
      },
      {
        id: "fact-14",
        statement: "Full month rent payment deadline approaches in 6 days.",
        evidenceId: "ev-14",
      },
    ],
    inferences: [
      {
        id: "inf-11",
        inference: "Life-threatening health crisis if insulin bridge is not secured before Friday insurance cancellation.",
        rationale: "Insulin without insurance carries prohibitive out-of-pocket costs and withdrawal risks diabetic ketoacidosis.",
        confidence: 0.99,
      },
      {
        id: "inf-12",
        inference: "Involuntary termination constitutes Qualifying Life Event (QLE) triggering immediate 60-day Special Enrollment Period for ACA / Medicaid.",
        rationale: "Loss of minimum essential coverage grants exemption from standard enrollment windows.",
        confidence: 0.97,
      },
    ],
    unknowns: [
      {
        id: "unk-11",
        question: "What is your estimated household income for the current calendar month?",
        whyNeeded: "Determines whether you qualify for instant Medicaid (under 138% FPL) or subsidized ACA marketplace credits.",
        blockedActionIds: ["act-12"],
        suggestedOptions: ["Under $1,700/mo (Medicaid eligible)", "$1,700 - $3,500/mo (ACA Subsidies)", "Above $3,500/mo"],
      },
    ],
    needs: [
      {
        id: "need-meds",
        category: "health_safety",
        title: "Urgent Insulin Refill & Bridge Access",
        description: "Secure immediate 30-day emergency insulin supply before Friday insurance termination.",
        urgency: "immediate_24h",
        trustState: "USER_PROVIDED",
        evidenceIds: ["ev-12", "ev-13"],
        whyReasoning: "Stated life-critical medication running out in 4 days. Must act prior to Friday insurance lapse.",
        systemIds: ["sys-pharmacy", "sys-communityhealth"],
        blockingNeedIds: [],
        actionIds: ["act-11"],
      },
      {
        id: "need-insurance",
        category: "health_safety",
        title: "Special Enrollment Healthcare Coverage",
        description: "File Qualifying Life Event application for expedited state healthcare transition.",
        urgency: "urgent_72h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-11", "ev-13"],
        whyReasoning: "Layoff eliminates coverage; eligible for zero-premium Medicaid or subsidized exchange plan.",
        systemIds: ["sys-medicaid"],
        blockingNeedIds: [],
        actionIds: ["act-12"],
      },
      {
        id: "need-unemployment",
        category: "financial",
        title: "State Unemployment Insurance Filing",
        description: "Submit initial UI claim to initiate weekly income benefits during waiting week.",
        urgency: "urgent_72h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-11"],
        whyReasoning: "Zero severance means immediate cash crunch; state benefits require 1-2 weeks processing delay.",
        systemIds: ["sys-labor"],
        blockingNeedIds: [],
        actionIds: ["act-13"],
      },
      {
        id: "need-rent",
        category: "shelter",
        title: "Eviction Prevention & Landlord Grace Period",
        description: "Formally request temporary 15-day rent hardship deferral and apply for municipal eviction diversion.",
        urgency: "urgent_72h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-14"],
        whyReasoning: "Rent due in 6 days with no incoming paycheck; early communication prevents notice-to-vacate filings.",
        systemIds: ["sys-evictionprevention"],
        blockingNeedIds: [],
        actionIds: ["act-14"],
      },
    ],
    systems: [
      {
        id: "sys-pharmacy",
        name: "Community Health Center & 340B Pharmacy",
        agencyType: "healthcare",
        purpose: "Emergency low-cost prescription bridge and urgent insulin co-pay relief.",
        contactChannel: "Local Community Health Clinic Direct Line",
        requiredDocuments: ["Prescription bottle / Rx number", "Proof of address"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-medicaid",
        name: "State Health Benefits Exchange",
        agencyType: "government",
        purpose: "Fast-track Medicaid enrollment under sudden zero-income qualification.",
        contactChannel: "healthcare.gov / state portal",
        requiredDocuments: ["Notice of termination / Layoff letter", "Last pay stub"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-labor",
        name: "State Department of Labor (Unemployment)",
        agencyType: "government",
        purpose: "Unemployment insurance weekly wage compensation.",
        contactChannel: "uiclaims.state.gov",
        requiredDocuments: ["Employer EIN", "W-2 / Pay stubs", "Direct deposit info"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-evictionprevention",
        name: "Municipal Eviction Diversion Hotline",
        agencyType: "government",
        purpose: "Emergency rental assistance grants and mediation.",
        contactChannel: "Call 3-1-1 or visit housinghelp.city.gov",
        requiredDocuments: ["Lease agreement", "Proof of hardship (layoff notice)"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
    ],
    actions: [
      {
        id: "act-11",
        needId: "need-meds",
        systemId: "sys-pharmacy",
        title: "Call Current Pharmacy to Expedite Final Insulin Fill BEFORE Friday",
        instruction: "Request an immediate 30-day or 90-day refill today while current employer insurance is active on file.",
        priority: "P0_critical",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "TODAY (Before 5:00 PM)",
        deliverableType: "phone_call",
        scriptOrTemplate: {
          headline: "Pharmacy Refill Script",
          body: "Hello, I am calling for an urgent refill on my insulin prescription [Rx#]. My employer insurance terminates this Friday, so I need this processed and billed through my active policy today.",
        },
        status: "pending",
      },
      {
        id: "act-12",
        needId: "need-insurance",
        systemId: "sys-medicaid",
        title: "Submit Special Enrollment Form for Health Insurance",
        instruction: "Select 'Loss of Employer Sponsored Coverage' as qualifying event to avoid penalty and guarantee continuous coverage.",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "Within 48 hours",
        deliverableType: "form_submission",
        status: "pending",
      },
      {
        id: "act-13",
        needId: "need-unemployment",
        systemId: "sys-labor",
        title: "Submit State Unemployment Claim Online",
        instruction: "File initial claim immediately to activate the state statutory waiting week.",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "Within 48 hours",
        deliverableType: "form_submission",
        status: "pending",
      },
      {
        id: "act-14",
        needId: "need-rent",
        systemId: "sys-evictionprevention",
        title: "Deliver Landlord Hardship Letter Requesting 14-Day Extension",
        instruction: "Proactively send notice of layoff and pending unemployment disbursement to forestall legal eviction filing.",
        priority: "P1_high",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: ["act-13"],
        timeframe: "By Tomorrow 12:00 PM",
        deliverableType: "notification",
        scriptOrTemplate: {
          headline: "Tenant Hardship Extension Letter",
          body: "Dear [Landlord Name], I am writing to notify you that I experienced an unexpected job layoff on [Date]. I have already filed for unemployment insurance. I am formally requesting a 14-day grace period on this month's rent due in 6 days while benefits process.",
        },
        status: "pending",
      },
    ],
    relationships: [
      {
        id: "rel-11",
        sourceId: "act-11",
        targetId: "need-meds",
        relationType: "resolves_need",
        label: "Averts medical catastrophe before policy cutoff",
      },
      {
        id: "rel-12",
        sourceId: "act-13",
        targetId: "act-14",
        relationType: "depends_on",
        label: "Unemployment filing confirmation required to support landlord extension",
      },
    ],
  },

  "elderly-caregiver": {
    id: "sit-elder-003",
    rawInput: {
      storyText:
        "My 82-year-old mother fell yesterday and fractured her wrist. The hospital wants to discharge her tomorrow afternoon, but she lives alone in a two-story home, has steep front stairs, cannot prepare meals with her cast, and her basic Medicare won't cover in-home aide assistance. I work full time two hours away.",
      hasMedia: false,
    },
    metadata: {
      analyzedAt: new Date().toISOString(),
      modelUsed: "gemini-2.5-flash (multimodal reasoning)",
      overallSeverity: "critical",
      summary:
        "High-risk unsafe hospital discharge of an 82-year-old vulnerable adult with physical injury into an inaccessible living environment without in-home caregiving support.",
      primaryDomain: "Geriatric Care Triage & Post-Acute Safety",
      isDemoOrSimulated: true,
    },
    evidence: [
      {
        id: "ev-21",
        source: "user_story",
        content: "My 82-year-old mother fell yesterday and fractured her wrist.",
        confidence: 1.0,
      },
      {
        id: "ev-22",
        source: "user_story",
        content: "The hospital wants to discharge her tomorrow afternoon",
        confidence: 1.0,
      },
      {
        id: "ev-23",
        source: "user_story",
        content: "she lives alone in a two-story home, has steep front stairs",
        confidence: 1.0,
      },
      {
        id: "ev-24",
        source: "user_story",
        content: "cannot prepare meals with her cast, and her basic Medicare won't cover in-home aide",
        confidence: 1.0,
      },
      {
        id: "ev-25",
        source: "user_story",
        content: "I work full time two hours away.",
        confidence: 1.0,
      },
    ],
    facts: [
      {
        id: "fact-21",
        statement: "Patient is 82 years old with acute wrist fracture following a fall.",
        evidenceId: "ev-21",
      },
      {
        id: "fact-22",
        statement: "Hospital plans acute discharge within approximately 24 hours.",
        evidenceId: "ev-22",
      },
      {
        id: "fact-23",
        statement: "Living quarters present severe architectural hazards (two-story, steep stairs).",
        evidenceId: "ev-23",
      },
      {
        id: "fact-24",
        statement: "Primary caregiver is geographically separated (2 hours away).",
        evidenceId: "ev-25",
      },
    ],
    inferences: [
      {
        id: "inf-21",
        inference: "High probability of repeat fall and rehospitalization within 72 hours if discharged home unassisted.",
        rationale: "Impaired balance, wrist cast preventing rail grip, and living alone make stair traversal hazardous.",
        confidence: 0.98,
      },
      {
        id: "inf-22",
        inference: "Hospital discharge planner has a statutory duty to prevent an 'unsafe discharge' under Medicare Conditions of Participation.",
        rationale: "Caregiver has legal right to appeal discharge notice through the Quality Improvement Organization (QIO).",
        confidence: 0.95,
      },
    ],
    unknowns: [
      {
        id: "unk-21",
        question: "Was the mother formally admitted as an inpatient for at least 3 midnights or on observation status?",
        whyNeeded: "Inpatient admission qualifies patient for 100% Medicare-covered Short-Term Subacute Rehab (SNF) placement.",
        blockedActionIds: ["act-22"],
        suggestedOptions: ["Admitted Inpatient (3 midnights)", "Observation Status Only", "Unsure / Need to ask doctor"],
      },
    ],
    needs: [
      {
        id: "need-discharge",
        category: "health_safety",
        title: "Discharge Delay & Unsafe Discharge Appeal",
        description: "Formally halt premature discharge until safe transitional care plan is established.",
        urgency: "immediate_24h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-22", "ev-23"],
        whyReasoning: "Discharging an injured 82-year-old to an empty multi-story home is medically unsafe under CMS rules.",
        systemIds: ["sys-hospital", "sys-qio"],
        blockingNeedIds: [],
        actionIds: ["act-21", "act-22"],
      },
      {
        id: "need-nutrition",
        category: "relief_aid",
        title: "Post-Acute Nutrition & Meal Delivery",
        description: "Activate emergency home-delivered meals due to inability to cook with arm cast.",
        urgency: "urgent_72h",
        trustState: "USER_PROVIDED",
        evidenceIds: ["ev-24"],
        whyReasoning: "User stated mother cannot prepare meals with her cast.",
        systemIds: ["sys-mow"],
        blockingNeedIds: [],
        actionIds: ["act-23"],
      },
      {
        id: "need-adaptation",
        category: "shelter",
        title: "Home Safety Adaptation & Medical Equipment",
        description: "Arrange first-floor temporary bed and grab-bar installation via Area Agency on Aging.",
        urgency: "urgent_72h",
        trustState: "AI_INFERRED",
        evidenceIds: ["ev-23"],
        whyReasoning: "Gemini identified stairs as fatal fall hazard; needs first-floor sleeping accommodation.",
        systemIds: ["sys-aaa"],
        blockingNeedIds: [],
        actionIds: ["act-24"],
      },
    ],
    systems: [
      {
        id: "sys-hospital",
        name: "Hospital Case Management & Social Work",
        agencyType: "healthcare",
        purpose: "Post-discharge placement and occupational therapy evaluation.",
        contactChannel: "Ask nursing station for Hospital Social Worker on duty",
        requiredDocuments: ["Medicare Card", "Health Care Proxy / Power of Attorney"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-qio",
        name: "Medicare Quality Improvement Org (QIO Appeal)",
        agencyType: "government",
        purpose: "Emergency statutory stay of hospital discharge pending independent medical review.",
        contactChannel: "1-800-MEDICARE or Regional QIO Hotline",
        requiredDocuments: ["Notice of Medicare Non-Coverage (NOMNC) form"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-mow",
        name: "County Meals on Wheels / Senior Nutrition",
        agencyType: "ngo_relief",
        purpose: "Emergency daily hot and cold meal delivery for convalescing seniors.",
        contactChannel: "seniorservices@countygov.org",
        requiredDocuments: ["Doctor dietary prescription if specialized"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
      {
        id: "sys-aaa",
        name: "Area Agency on Aging (AAA)",
        agencyType: "government",
        purpose: "Free assistive equipment loans and family caregiver respite funding.",
        contactChannel: "eldercare.acl.gov / 1-800-677-1116",
        requiredDocuments: ["Proof of age (82yo) and county residence"],
        simulatedStatus: "simulated_live",
        disclaimer: "Simulated directory listing for demonstration.",
      },
    ],
    actions: [
      {
        id: "act-21",
        needId: "need-discharge",
        systemId: "sys-hospital",
        title: "Instruct Hospital Case Manager to Log 'Unsafe Discharge' Objection",
        instruction: "Notify the attending physician and social worker immediately that the home environment is physically hazardous and no caregiver is present.",
        priority: "P0_critical",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: [],
        timeframe: "TODAY (Before 3:00 PM)",
        deliverableType: "phone_call",
        scriptOrTemplate: {
          headline: "Case Worker Objection Script",
          body: "Hello, I am calling regarding my mother [Mother Name, Room #]. I am notifying you in writing and by phone that a discharge tomorrow is unsafe. She lives alone in a 2-story home with steep stairs, has a fractured wrist preventing rail stabilization, and I live 2 hours away. Under Medicare CoP 482.43, the hospital cannot discharge her to an unsafe setting.",
        },
        status: "pending",
      },
      {
        id: "act-22",
        needId: "need-discharge",
        systemId: "sys-hospital",
        title: "Request Order for Subacute Short-Stay Physical Rehab (SNF)",
        instruction: "Request that the physician order transitional inpatient physical therapy evaluation to bridge mobility recovery.",
        priority: "P0_critical",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: ["act-21"],
        timeframe: "Before Discharge Planning Rounds Tomorrow 9:00 AM",
        deliverableType: "in_person_visit",
        status: "pending",
      },
      {
        id: "act-23",
        needId: "need-nutrition",
        systemId: "sys-mow",
        title: "Enroll Mother in Expedited Post-Hospital Meal Delivery",
        instruction: "Call local senior services to initiate priority 14-day recuperative meal delivery.",
        priority: "P1_high",
        trustState: "USER_PROVIDED",
        prerequisiteActionIds: [],
        timeframe: "Tomorrow morning",
        deliverableType: "phone_call",
        status: "pending",
      },
      {
        id: "act-24",
        needId: "need-adaptation",
        systemId: "sys-aaa",
        title: "Request Area Agency on Aging First-Floor Safety Assessment",
        instruction: "Arrange temporary hospital bed rental for the living room to avoid all stair traversal.",
        priority: "P2_normal",
        trustState: "AI_INFERRED",
        prerequisiteActionIds: ["act-21"],
        timeframe: "Within 48 hours",
        deliverableType: "form_submission",
        status: "pending",
      },
    ],
    relationships: [
      {
        id: "rel-21",
        sourceId: "act-21",
        targetId: "act-22",
        relationType: "triggers",
        label: "Unsafe discharge objection initiates subacute rehab referral",
      },
      {
        id: "rel-22",
        sourceId: "act-21",
        targetId: "act-24",
        relationType: "depends_on",
        label: "Home safety adaptations required before any eventual homecoming",
      },
    ],
  },
};
